export const ASSIGN_ID = "assignid",
  POLL_DATA = "polldata",
  CREATE_POLL = "createpoll",
  GET_POLL = "getpoll",
  CREATED_POLL = "createdpoll",
  JOIN_ROOM = "joinroom",
  VOTE = "vote",
  BERROR = "err",
  REMOVE_ROOM = "removefromroom";
