version: "3"
services:
  redis:
    build: myredisdb
    ports:
      - "4200:4200"
    container_name: myredisdb
    restart: always

  backend:
    build: backend
    ports:
      - "5002:5002"
    container_name: gopollv2_backend
    restart: always
    environment:
      - PORT=5002
      - DBPASS=ihmc_sucks
